//User related actions
export const USERDATALOADING ='USERDATALOADING'
export const USERDATASUCCESS ='USERDATASUCCESS'
export const USERDATAFAILURE ='USERDATAFAILURE'


// todo reducer related actions
export const TODODATALOADING ='TODODATALOADING'
export const TODODATASUCCESS = 'TODODATASUCCESS'
export const TODODATAFAILURE ='TODODATAFAILURE'